all:
	g++ -I /usr/local/include -L /usr/local/lib -o kid -std=c++11 -lSDL2main -lSDL2 -lSDL2_image kid.cc 
win:
	g++ -I /mingw64/include -L /mingw64/lib -o kid -std=c++11 kid.cc -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
